#!/bin/bash

set -e

sudo apt-get update
sudo apt-get install -y wget git build-essential autoconf libtool gettext automake

cd /tmp/mono

MONO_PREFIX=/app/mono
export DYLD_FALLBACK_LIBRARY_PATH=$MONO_PREFIX/lib:$DYLD_LIBRARY_FALLBACK_PATH
export LD_LIBRARY_PATH=$MONO_PREFIX/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$MONO_PREFIX/include
export ACLOCAL_PATH=$MONO_PREFIX/share/aclocal
export PKG_CONFIG_PATH=$MONO_PREFIX/lib/pkgconfig
export PATH=$MONO_PREFIX/bin:$PATH

./autogen.sh
./configure --prefix=$MONO_PREFIX \
  --disable-moonlight --disable-nls --enable-minimal=aot,profiler,debug,logging \
  --disable-libraries --disable-boehm --with-mcs-docs=no \
  --with-profile2=no

make get-monolite-latest
make -j4
make install
