#!/bin/bash

sudo apt-get update
sudo apt-get install -y build-essential autoconf libtool gettext automake

cd /tmp/mono

MONO_PREFIX=/app/mono
export DYLD_FALLBACK_LIBRARY_PATH=$MONO_PREFIX/lib:$DYLD_LIBRARY_FALLBACK_PATH
export LD_LIBRARY_PATH=$MONO_PREFIX/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$MONO_PREFIX/include
export ACLOCAL_PATH=$MONO_PREFIX/share/aclocal
export PKG_CONFIG_PATH=$MONO_PREFIX/lib/pkgconfig
export PATH=$MONO_PREFIX/bin:$PATH

./autogen.sh --prefix=$MONO_PREFIX
make get-monolite-latest
make -j4
make install