#!/bin/bash

set -e
set -x

VERSION=`cat ./latest | cut -c 1-12`

cp out/* $CIRCLE_ARTIFACTS

git config --global user.email "AdamBurgess@users.noreply.github.com"
git config --global user.name "Adam Burgess"
git clone git@github.com:AdamBurgess/heroku-buildpack-mono.git
cd heroku-buildpack-mono

#delete any pre-existing tags
if git rev-parse $VERSION >/dev/null 2>&1
then
    git tag -d $VERSION && git push --delete origin $VERSION
fi

echo $VERSION>latest
git add latest
git commit -m "built mono: $VERSION." || true
git tag $VERSION
git push
git push --tags

go get github.com/tcnksm/ghr
ghr \
    -u AdamBurgess \
    -r heroku-buildpack-mono \
    $VERSION ../out
