#!/bin/bash

set -e
VERSION=`cat ./latest`

pushd

tar cfz mono.tar.gz mono

cp mono.tar.gz $CIRCLE_ARTIFACTS

git config --global user.email "AdamBurgess@users.noreply.github.com"
git config --global user.name "Adam Burgess"
git clone git@github.com:AdamBurgess/heroku-buildpack-mono.git
cd heroku-buildpack-mono

echo $VERSION>latest
git add latest
git commit -m "built mono version $VERSION."
git tag $VERSION
git push
git push --tags

popd

node deploy-to-github $VERSION $HOME/mono.tar.gz