#!/bin/bash

set -e
set -x

VERSION=`cat ./latest`

cp out/* $CIRCLE_ARTIFACTS

go get github.com/tcnksm/ghr

git clone git@github.com:AdamBurgess/heroku-buildpack-mono.git
cd heroku-buildpack-mono

#delete any pre-existing tags
if git rev-parse $VERSION >/dev/null 2>&1
then
    git tag -d $VERSION && git push --delete origin $VERSION
fi

echo $VERSION>latest
git config user.name "Adam Burgess [circleci]"
git config user.email "email@example.com"
git add latest
git commit -m "built mono: $VERSION." || true
git tag $VERSION
git push
git push --tags

# let github sort stuff out
sleep 5

ghr \
    -u AdamBurgess \
    -r heroku-buildpack-mono \
    --delete \
    $VERSION ../out
