#!/bin/bash

docker run \
    -v ~/git/mono/mono:/tmp/mono \
    -v $PWD/build:/build \
    -v ~/mono:/app/mono \
    ubuntu:14.04 \
    "bash /build"

cd ~
tar -zcvf mono.tar.gz mono
mv mono.tar.gz $CIRCLE_ARTIFACTS