#!/bin/bash

docker run \
    -v ~/git/mono/mono:/tmp/mono \
    -v $PWD/build:/build \
    -v ~/output:/app/mono \
    ubuntu:14.04 \
    bash -c "sudo apt-get update; sudo apt-get install -y build-essential autoconf libtool gettext automake; bash /build"

cd ~
tar -zcvf mono.tar.gz output
mv mono.tar.gz $CIRCLE_ARTIFACTS