#!/bin/bash

set -e
set -x

git config --global user.email "AdamBurgess@users.noreply.github.com"
git config --global user.name "Adam Burgess"
git config --global push.default simple

VERSION=`cat ./latest | cut -c 1-12`

if [[ ! -e mono ]]; then
  git clone https://github.com/mono/mono.git mono
fi

pushd mono
git fetch origin master
git checkout -f $VERSION
popd